name: Unit Tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: npm ci

      - run: npm test
